{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T12:47:12.302Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T12:49:51.564Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T13:54:24.049Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T13:55:41.826Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T13:59:27.789Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T14:03:22.197Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T14:06:45.893Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T14:08:58.738Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: password authentication failed for user \"username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"332","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"cv-builder-api","stack":"SequelizeConnectionError: password authentication failed for user \"username\"\n    at Client._connectionCallback (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:518:28)\n    at Connection.emit (node:domain:489:12)\n    at D:\\Resume _Generator\\backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (D:\\Resume _Generator\\backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-09-04T14:09:16.291Z"}
{"level":"error","message":"❌ PostgreSQL connection failed: permission denied for schema public","name":"SequelizeDatabaseError","original":{"code":"42501","file":"aclchk.c","length":99,"line":"2845","name":"error","position":"28","routine":"aclcheck_error","severity":"ERROR","sql":"CREATE TABLE IF NOT EXISTS \"users\" (\"id\" UUID , \"name\" VARCHAR(100) NOT NULL, \"email\" VARCHAR(255) NOT NULL UNIQUE, \"password\" VARCHAR(255) NOT NULL, \"avatar\" VARCHAR(255), \"profession\" VARCHAR(100), \"isVerified\" BOOLEAN DEFAULT false, \"resetPasswordToken\" VARCHAR(255), \"resetPasswordExpires\" TIMESTAMP WITH TIME ZONE, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL, \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (\"id\"));"},"parameters":{},"parent":{"code":"42501","file":"aclchk.c","length":99,"line":"2845","name":"error","position":"28","routine":"aclcheck_error","severity":"ERROR","sql":"CREATE TABLE IF NOT EXISTS \"users\" (\"id\" UUID , \"name\" VARCHAR(100) NOT NULL, \"email\" VARCHAR(255) NOT NULL UNIQUE, \"password\" VARCHAR(255) NOT NULL, \"avatar\" VARCHAR(255), \"profession\" VARCHAR(100), \"isVerified\" BOOLEAN DEFAULT false, \"resetPasswordToken\" VARCHAR(255), \"resetPasswordExpires\" TIMESTAMP WITH TIME ZONE, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL, \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (\"id\"));"},"service":"cv-builder-api","sql":"CREATE TABLE IF NOT EXISTS \"users\" (\"id\" UUID , \"name\" VARCHAR(100) NOT NULL, \"email\" VARCHAR(255) NOT NULL UNIQUE, \"password\" VARCHAR(255) NOT NULL, \"avatar\" VARCHAR(255), \"profession\" VARCHAR(100), \"isVerified\" BOOLEAN DEFAULT false, \"resetPasswordToken\" VARCHAR(255), \"resetPasswordExpires\" TIMESTAMP WITH TIME ZONE, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL, \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (\"id\"));","stack":"Error\n    at Query.run (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\postgres\\query.js:76:25)\n    at D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.createTable (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:229:12)\n    at async Function.sync (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\model.js:1353:7)\n    at async Sequelize.sync (D:\\Resume _Generator\\backend\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async connectDB (D:\\Resume _Generator\\backend\\src\\utils\\database.ts:34:5)","timestamp":"2025-09-04T18:44:48.575Z"}
